server:
  port: 8082
  
spring:
  application:
    name: SYSTEM-CONFIG
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost