server:
  port: 8093
  
spring:
  application:
    name: COMMON-SERVICE
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost