server:
  port: 8084
  
spring:
  application:
    name: OWNER-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nova_v1_5
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update    
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost