cloud:
  aws:
    credentials:
      access-key: AKIA5VELUWCBBOPT63VU
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false
       
server:
  port: 8094
  
spring:
  application:
    name: COMMON-SERVICE
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error